/*
 * Copyright 2015 Hongxin Telecommunication Technologies Co, Ltd.,
 * Wuhan, Hubei, China. All rights reserved.
 */

/*
 * DrawPanel.java
 *
 * Created on 2017-12-11, 19:14:54
 */

package com.cw.pack;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author chenwei
 */
public class DrawPanel extends javax.swing.JPanel
{

	private int type;
	private Car car;
    /** Creates new form DrawPanel */
    public DrawPanel(int type, Car car)
	{
        initComponents();
		this.car = car;
		this.type = type;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     @Override
     protected void paintComponent(Graphics g) {
        super.paintComponent(g);
		Graphics2D g2d = (Graphics2D) g.create();
		drawCar(g2d);
		for(Device dev:car.getPutDevices())
		{
			int length = (int)dev.getLength();
			int width = (int)dev.getWidth();
			int high = (int)dev.getHigh();
			for(int i=0;i<dev.getNumber();i++)
			{
//				drawRect(g2d, dev, i);
			}
		}
	}
	private void drawCar(Graphics2D g2d)
	{
		int carLength = (int)car.getLength();
		int carWidth = (int)car.getWidth();
		int carHigh = (int)car.getHigh();
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setColor(Color.BLACK);
		
		int drawCarLen = this.getWidth() - 10;
		
		float rate = (float)drawCarLen/carLength;
		switch(type)
		{
			case 1://车左侧面
				g2d.drawString("左侧面", 10, 15);
				float drawCarWid = carHigh*rate;
				float start = (this.getHeight() - drawCarWid)/2;
				g2d.drawRect(5, (int)start, drawCarLen, (int)drawCarWid);
				
				
				break;
			case 2://车右侧面
				g2d.drawString("右侧面", 10, 15);
				float drawCarWid1 = carHigh*rate;
				float start1 = (this.getHeight() - drawCarWid1)/2;
				g2d.drawRect(5, (int)start1, drawCarLen, (int)drawCarWid1);
				break;
			case 3://车顶侧面
				g2d.drawString("顶侧面", 10, 15);
				float drawCarWid2 = carWidth*rate;
				float start2 = (this.getHeight() - drawCarWid2)/2;
				g2d.drawRect(5, (int)start2, drawCarLen, (int)drawCarWid2);
				break;
			default:
				break;
		}
			

        // 1. 绘制一个矩形: 起点(30, 20), 宽80, 高100
//        g2d.drawRect(30, 20, 80, 100);
//		g2d.drawRect(120, 20, 80, 100);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
