/*
 * Copyright 2015 Hongxin Telecommunication Technologies Co, Ltd.,
 * Wuhan, Hubei, China. All rights reserved.
 */

/*
 * ResultDialog.java
 *
 * Created on 2017-11-28, 19:46:48
 */

package com.cw.pack;

import com.cw.pack.render.ButtonRender;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chenwei
 */
public class ResultDialog extends javax.swing.JDialog
{

    /** Creates new form ResultDialog */
    public ResultDialog(java.awt.Frame parent, List<Car> cars, boolean modal)
	{
        super(parent, modal);
        initComponents();
		carTxt.setText(cars.size()+"");
		Map<String,Integer> mapCars = new HashMap<String, Integer>();
		for(Car car:cars)
		{
			Integer num = mapCars.get(car.getName());
			if(num==null)
			{
				num = 0;
			}
			num++;
			mapCars.put(car.getName(), num);
		}
		String details = "其中:";
		for(Map.Entry<String, Integer> entry:mapCars.entrySet())
		{
			details += entry.getKey()+"--"+entry.getValue()+"辆,";
		}
		details = details.substring(0, details.length()-1);
		detailTxt.setText(details);
		initTable(cars);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carInfo = new javax.swing.JTable();
        detailTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("计算结果");

        jLabel1.setText("所需车辆信息");

        jLabel2.setText("共");

        carTxt.setEditable(false);
        carTxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        carTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("辆");

        close.setText("关闭");
        close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeActionPerformed(evt);
            }
        });

        carInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "序号", "设备种类", "设备数量", "视图"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        carInfo.setRowHeight(20);
        jScrollPane1.setViewportView(carInfo);
        if (carInfo.getColumnModel().getColumnCount() > 0)
        {
            carInfo.getColumnModel().getColumn(0).setPreferredWidth(80);
            carInfo.getColumnModel().getColumn(0).setMaxWidth(100);
            carInfo.getColumnModel().getColumn(3).setMinWidth(100);
            carInfo.getColumnModel().getColumn(3).setPreferredWidth(100);
            carInfo.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        detailTxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(close))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(carTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(detailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(close)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeActionPerformed
    {//GEN-HEADEREND:event_closeActionPerformed
        // TODO add your handling code here:
		this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carInfo;
    private javax.swing.JTextField carTxt;
    private javax.swing.JButton close;
    private javax.swing.JLabel detailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

	private void initTable(List<Car> cars)
	{
		((DefaultTableCellRenderer)carInfo.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

		carInfo.getColumnModel().getColumn(3).setCellEditor(new ButtonRender(cars));//设置编辑器
		carInfo.getColumnModel().getColumn(3).setCellRenderer(new ButtonRender(cars));			
		for(int i=0;i<cars.size();i++)
		{
			List<Weapon> devs = cars.get(i).getPutDevices();
			int totalDevNum = 0;
			for(Weapon dev:devs)
			{
				totalDevNum += dev.getNumber();
			}
			((DefaultTableModel)carInfo.getModel()).addRow(new Object[]{i+1, devs.size(),totalDevNum});
		}
	}

}
